### ISSUE TITLE
您好，代码复现的过程中报错了

### ISSUE THREAD

**Issue by yangye19960922** [arleigh418/Paper-Implementation-DSTP-RNN-For-Stock-Prediction-Based-On-DA-RNN#1]
File "DSTP_RNN.py", line 128, in forward
    x_tilde.permute(0, 2, 1),
RuntimeError: number of dims don't match in permute

我在服务器运行您的代码，报出了这样的错误

**Comment by arleigh418** [comment]
已修復。因為測試而將:X.permute(0, 2, 1)，改為concat x_tilde，已修正為concat X.
若是需要進行測試的話，實際上x_tilde的排列方式並非(0, 2, 1)，請根據其他tensor維度進行排列。
很感謝您提出的問題。
