### ISSUE TITLE
用nasdaq100_padding数据效果和DA-RNN差不多啊

### ISSUE THREAD

**Issue by lzh66** [arleigh418/Paper-Implementation-DSTP-RNN-For-Stock-Prediction-Based-On-DA-RNN#2]

**Comment by lzh66** [comment]
顺便问问有DSTP-RNN-Ⅱmodel的实现吗

**Comment by arleigh418** [comment]
Hi ! 感謝您提出討論，經由後續測試，發現到此模型並非是全面超越DA-RNN，至於是否此模型更適用於部分情境例如範例中的股價較低且波動較小的股票類型則因為實驗樣本過少而在此不敢保證，僅是嘗試的性質。
若是您有更多的測試及結果，非常歡迎您提出一同討論，至於DSTP-RNN-Ⅱmodel則尚未嘗試，若有機會會來研究看看，因為是試做且敝人並非作者，所以關於正確性也很歡迎您檢閱之後一起討論。
