### ISSUE TITLE
model.test问题

### ISSUE THREAD

**Issue by fxl-fxl** [arleigh418/Paper-Implementation-DSTP-RNN-For-Stock-Prediction-Based-On-DA-RNN#4]
为什么训练之后保存的参数，之后test函数根本就没用到，所以为什么要训练呢
def test(self, on_train=False):

**Comment by arleigh418** [comment]
Hi, 您所指的參數跟所謂的使用指的是什麼? 您能否提供範例以利我們討論一下。
p.s. github上敝人較不會即時的回覆，如果您緊急，請mail給我。

**Comment by fxl-fxl** [comment]
> Hi, 您所指的參數跟所謂的使用指的是什麼? 您能否提供範例以利我們討論一下。
> p.s. github上敝人較不會即時的回覆，如果您緊急，請mail給我。

您好，那个你最后433行的代码pred = model.test() ，求出来的数据和测试集数据的shape大小不一致，请问是什么原因，还有能告诉我你的邮箱吗

**Comment by fxl-fxl** [comment]
> Hi, 您所指的參數跟所謂的使用指的是什麼? 您能否提供範例以利我們討論一下。
> p.s. github上敝人較不會即時的回覆，如果您緊急，請mail給我。

y_pred_price[i:(i + self.batch_size)] = self.Decoder(input_encoded , y_history).cpu().data.numpy()[:, 0]
model.test()  改成这个shape就相同了

**Comment by arleigh418** [comment]
Hi! 非常感謝您的Feedback! 週日我會花時間再度確認您的修正建議！
如果有任何問題也請您如此次不吝指教！

Thanks!
Arleigh

fxl-fxl <notifications@github.com>於 2020年8月14日 週五，下午3:28寫道：

**Comment by arleigh418** [comment]
Hi ! 經過測試及檢查，請容許我一併在此說明，此Issue將會Open一周直至此問題無其他異議。
您確實發現了失誤存在，很幸運的是，在我們的實驗Case中因為測試集的shape較batch size小，因此此失誤並未被發現。
在舊版本中，我們誤將y_pred_price直接取代為預測出來的矩陣，而非原作者的將測試集以batch size的順序推移取代矩陣中0的數值為預測值。
但如同上所說，我們非常幸運地因當測試集小於batch size則不會有依照batch size的順序推移的情況，若是直接取代應也不會造成結果上的錯誤，但此幸運也造成我們沒有發現此項重大失誤。

在測試樣本大於batch size的情況，確確實實會偏差，目前已修復，確保萬一將會進行復測，萬分感謝您的提醒以及協助。
