### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by DeastinY** [arleigh418/Paper-Implementation-DSTP-RNN-For-Stock-Prediction-Based-On-DA-RNN#5]
Hi, I get the following error:

```
  File "dstp.py", line 480, in <module>
    model.train(X, y)
  File "dstp.py", line 262, in train
    loss = self.train_forward(x, y_prev, y_gt)
  File "dstp.py", line 294, in train_forward
    input_weighted, input_encoded = self.Encoder(
  File "python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "dstp.py", line 140, in forward
    self.encoder_lstm2.flatten_parameters()
  File "python3.8/site-packages/torch/nn/modules/rnn.py", line 149, in flatten_parameters
    torch._cudnn_rnn_flatten_weight(
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```
Could this be due to flatten_parameters() being called while only training with a single GPU? Other idea I had was, that the backpropagation is not initialized correctly somewhere and grows until it at some time runs out of memory. I checked through the parts (especially initializing encoder/decoder during training) but it all seems fined.
I'm running Cuda 11.0.3 for what it's worth, but had the same issues with Cuda 10.6

**Comment by arleigh418** [comment]
No problem on CUDA 10.0. Maybe you can try reducing the batch size?

**Comment by DeastinY** [comment]
I'm using a different dataset, but it's not a memory issue. Never goes past 2 GB of RAM. With reduced batch size it just takes longer to fail :confused:

**Comment by arleigh418** [comment]
According to my understanding, there are two possibilities for this problem:
1.Memory issue (reduce batch size will be fine, but it seems not this problem in your case)
2.Versions of pytorch and cudatoolkit issue (I just follow pytorch official guidelines, and download cudnn from [here](https://developer.nvidia.com/rdp/cudnn-archive)) 

Maybe you can try this as below , but it may reduce learning efficiency : 
`torch.backends.cudnn.benchmark = true`
