### ISSUE TITLE
A question of multi-step prediction

### ISSUE THREAD

**Issue by guoyucs** [arleigh418/Paper-Implementation-DSTP-RNN-For-Stock-Prediction-Based-On-DA-RNN#6]
Thank you so much for seeing your code, and I have a question that hopes answered by you. In the paper, the author said that DSTP-RNN can well solve the long-term prediction problem. But in my experiment, the generalization performance of DSTP-RNN is poor for multi-step prediction. I would like to ask you about the effect of multi-step prediction in your experiment. Thank you very much.

**Comment by arleigh418** [comment]
Actually I also get the bad result in multi-step prediction.(Try to use 7 days data to predict stock price between next week). 
I’m not sure if I misunderstood the author’s meaning, and I look forward to the author's own this paper's code on Github.

But in my experience, both DARNN and DSTP-RNN  are not good at multi-step prediction(compare with one-step prediction, mean using last 7 days to predict next stock price). 
Welcome for discussion, and thanks for your question.
