### ISSUE TITLE
Nasdaq100 Stock data set

### ISSUE THREAD

**Issue by danielh4067** [arleigh418/Paper-Implementation-DSTP-RNN-For-Stock-Prediction-Based-On-DA-RNN#7]
Hi!
First of all thanks for this clear implementation!
I would like to know where can I made '.csv' dataset like you used in your implementation? And also what is the interval tik time between every sample?

thanks
Daniel

**Comment by arleigh418** [comment]
Hi,
Thanks for your question.This data set come from [here](https://finance.yahoo.com/quote/2324.TW?p=2324.TW),  and I use [TA package](https://github.com/bukosabino/ta) to get the technical analysis info.BTW, this is the daily stock price information.
